name: Daily EPR Update
on:
  schedule:
    - cron: '0 0 * * *' # This runs every night at midnight
  workflow_dispatch: # This lets you run it manually with one click

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install tools
        run: pip install requests beautifulsoup4
      - name: Run Scraper
        run: python scraper.py
